### ISSUE TITLE
ModuleNotFoundError: No module named '_snowboydetect'

### ISSUE THREAD

**Issue by ahbon123** [wzpan/wukong-robot#101]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**操作系统**

Ubuntu 18.04

**问题描述**

```
Traceback (most recent call last):
  File "/home/x/文档/GitHub/wukong-robot/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'snowboy._snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/x/文档/GitHub/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/x/文档/GitHub/wukong-robot/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/x/文档/GitHub/wukong-robot/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'
```

**Comment by wzpan** [comment]
> 我已确认在 Github issue 页、常见问题页、文档 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

你确定吗？

- 常见问题页第一个问题：https://github.com/wzpan/wukong-robot/wiki/troubleshooting#%E5%90%AF%E5%8A%A8%E6%8A%A5%E9%94%99
- 文档页：https://wukong.hahack.com/#/install?id=_4-%e7%bc%96%e8%af%91-_snowboydetectso

**Comment by ahbon123** [comment]
可以了，谢谢啦

**Comment by Kevin369** [comment]
你好我也遇到相同的问题，我生成了_snowboydetect.so，cp命令不能执行，我把他手动拷贝到了wukong-robot下面的snowboy路径下，然后还是报这个错误，然后我把生成的swig-3.0.10下面的snowboy文件夹替换了wukong-robot下面的snowboy，结果还是不行，是生成的有问题吗？你是怎么解决的？新手不太会，万分感谢。

**Comment by Kevin369** [comment]
打扰了已解决，重新装了一遍就好了，很是纳闷，可能某个过程有漏掉的错误没注意
