### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by jackeyt** [wzpan/wukong-robot#102]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Ubuntu 18.04@ARM32

**问题描述**
运行`python3 wukong.py`出现提示编码格式错误，按道理来说python3已经不需要自己转为`utf-8`，但运行时仍会报错，尝试这网上的方法，手动强制转码，依旧无解~

```
Traceback (most recent call last):
  File "wukong.py", line 8, in <module>
    from server import server
  File "/home/fire/wukong-robot/server/server.py", line 323, in <module>
    "cookie_secret": config.get('/server/cookie_secret', "__GENERATE_YOUR_OWN_RANDOM_VALUE_HERE__"),
  File "/home/fire/wukong-robot/robot/config.py", line 120, in get
    init()
  File "/home/fire/wukong-robot/robot/config.py", line 34, in init
    doInit(constants.getConfigPath())
  File "/home/fire/wukong-robot/robot/config.py", line 59, in doInit
    _config = yaml.safe_load(f)
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/fire/.local/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 16: ordinal not in range(128)

```

**复现步骤**

**Comment by wzpan** [comment]
locale 问题。参考[这里](https://wukong.hahack.com/#/mic-choices?id=%e8%a7%a3%e5%86%b3-unicode-%e7%bc%96%e7%a0%81%e9%97%ae%e9%a2%98)解决。

**Comment by jackeyt** [comment]
已经试过了，问题依旧。。。

**Comment by jackeyt** [comment]
解决了，原来是配置文件的原因，我把它强制转为`utf-8`就好了，之前是在windows上编辑的
