### ISSUE TITLE
机器人反问用户时，没有时间说话，自动进入下一轮

### ISSUE THREAD

**Issue by goxofy** [wzpan/wukong-robot#107]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

树莓派 raspbian

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

用户：播放网易云音乐
悟空：你想播放什么？我能帮你要到推荐歌曲，推荐歌单或是你的歌单，甚至搜索某歌手或歌名噢？

到这一步之后，用户没有时间说话，“嘀”声之后开始录音，然后瞬间结束录音，然后持续返回

悟空：岔开话题，到底想听哪张歌单呀~混蛋！
悟空：岔开话题，到底想听哪张歌单呀~混蛋！
悟空：岔开话题，到底想听哪张歌单呀~混蛋！
悟空：岔开话题，到底想听哪张歌单呀~混蛋！

用户没有说话的机会。。

日志输出有报错，如下：
```
INFO:__main__:开始录音
INFO:robot.Conversation:结束录音
INFO:robot.ASR:baidu-asr 语音识别到了：['哦，播放网易云音乐，']
INFO:robot.Brain:'哦，播放网易云音乐，' 命中技能 NeteaseMusic
INFO:robot.Conversation:命中缓存，播放缓存语音
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
CRITICAL:snowboy:[Errno Device unavailable] -9985
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmp0dzpontp.mp3
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
CRITICAL:snowboy:[Errno Device unavailable] -9985
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmpnngpy0qz.mp3
```

**Comment by wzpan** [comment]
遇到 -9985 错误了。装了 pulseaudio 没

**Comment by 1341290135** [comment]
MacBook ，按照文档，用的一下两个命令：

brew install portaudio sox ffmpeg
pip3 install pyaudio

**Comment by goxofy** [comment]
> 遇到 -9985 错误了。装了 pulseaudio 没

装了，宿主机和docker里面都装了

**Comment by goxofy** [comment]
我感觉是播放完beep_hi之后，录音设备没有就绪，导致snowboy调用失败，然后就结束录音了

**Comment by wzpan** [comment]
@goxofy 试试将 robot/Conversation.py 里的[这句话](https://github.com/wzpan/wukong-robot/blob/master/robot/Conversation.py#L217)去掉前面的注释，看看效果？

**Comment by 1341290135** [comment]
试了，还是一样。

===================================================================
huangbodeMacBook-Pro:wukong-robot rain$ python3 wukong.py 

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键






^\Quit: 3
huangbodeMacBook-Pro:wukong-robot rain$ vi robot/Conversation.py 
huangbodeMacBook-Pro:wukong-robot rain$ brew install portaudio sox ffmpeg
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

Warning: portaudio 19.6.0 is already installed and up-to-date
To reinstall 19.6.0, run `brew reinstall portaudio`
Warning: sox 14.4.2_3 is already installed and up-to-date
To reinstall 14.4.2_3, run `brew reinstall sox`
Warning: ffmpeg 4.2.2_1 is already installed and up-to-date
To reinstall 4.2.2_1, run `brew reinstall ffmpeg`
huangbodeMacBook-Pro:wukong-robot rain$ pip3 install pyaudio
Requirement already satisfied: pyaudio in /usr/local/lib/python3.7/site-packages (0.2.11)

**Comment by 1341290135** [comment]
masOs Catalina 10.15.3

**Comment by goxofy** [comment]
@wzpan 这个sleep我之前试过了，不管用，我还在[第219行](https://github.com/wzpan/wukong-robot/blob/master/robot/Conversation.py#L219)也增加了sleep，依旧不管用

**Comment by 1341290135** [comment]
装了python多个版本，不知道会不会有影响。
用3.7，还是后台发消息可以，语音不行。

huangbodeMacBook-Pro:wukong-robot rain$ python3
python3            python3.7          python3.7m         
python3-config     python3.7-config   python3.7m-config  
huangbodeMacBook-Pro:wukong-robot rain$ python3.7 wukong.py 

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5000
            如需退出，可以按 Ctrl-4 组合键


INFO:robot.AI:emotibot 回答：吼！看到你每天精神满满的和我打招呼，我就觉得充满活力！
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/var/folders/np/ql8g663d0_96tq6f6dz5f2zh0000gp/T/tmp35pjwv5z.mp3
INFO:robot.Conversation:True
INFO:robot.Conversation:onSay: 吼！看到你每天精神满满的和我打招呼，我就觉得充满活力！, http://0.0.0.0:5000/audio/8ca5f2ae3656e0012348ec7f311cb103.mp3
INFO:robot.AI:emotibot 回答：我是谁？我是叮当啊，一个从云端网络来到你身边的专属精灵~
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/var/folders/np/ql8g663d0_96tq6f6dz5f2zh0000gp/T/tmpmndg_17s.mp3
INFO:robot.Conversation:True
INFO:robot.Conversation:onSay: 我是谁？我是叮当啊，一个从云端网络来到你身边的专属精灵~, http://0.0.0.0:5000/audio/4536d640b8a6d9c2f3cf37dd2a5975a2.mp3

**Comment by 1341290135** [comment]
日志：
========================================================
2020-02-10 00:27:27,768 - robot.ASR - ASR.py - get_engine_by_slug - line 183 - INFO - 使用 baidu-asr ASR 引擎
2020-02-10 00:27:27,769 - robot.AI - AI.py - get_robot_by_slug - line 236 - INFO - 使用 emotibot 对话机器人
2020-02-10 00:27:27,769 - robot.TTS - TTS.py - get_engine_by_slug - line 261 - INFO - 使用 baidu-tts TTS 引擎
2020-02-10 00:27:27,769 - robot.NLU - NLU.py - get_engine_by_slug - line 205 - INFO - 使用 unit NLU 引擎
2020-02-10 00:27:27,771 - robot.plugin_loader - plugin_loader.py - init_plugins - line 62 - INFO - 插件 Camera 已被禁用
2020-02-10 00:27:27,772 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 CleanCache 加载成功 
2020-02-10 00:27:27,773 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Echo 加载成功 
2020-02-10 00:27:27,778 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Email 加载成功 
2020-02-10 00:27:27,781 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Geek 加载成功 
2020-02-10 00:27:27,783 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 LocalPlayer 加载成功 
2020-02-10 00:27:27,784 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Poem 加载成功 
2020-02-10 00:27:27,785 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Volume 加载成功 
2020-02-10 00:27:27,787 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 BaiduFM 加载成功 
2020-02-10 00:27:27,789 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 BaiduMap 加载成功 
2020-02-10 00:27:27,822 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 ControMqtt 加载成功 
2020-02-10 00:27:27,823 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Direction 加载成功 
2020-02-10 00:27:27,824 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 EmailMyPC 加载成功 
2020-02-10 00:27:27,826 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Halt 加载成功 
2020-02-10 00:27:27,827 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Hass 加载成功 
2020-02-10 00:27:27,828 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 HeadlineNews 加载成功 
2020-02-10 00:27:27,830 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Lamp 加载成功 
2020-02-10 00:27:27,841 - robot.plugin_loader - plugin_loader.py - init_plugins - line 39 - WARNING - 插件 NeteaseMusic 加载出错，跳过
Traceback (most recent call last):
  File "/opt/robot/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rain/.wukong/contrib/NeteaseMusic.py", line 11, in <module>
    from sdk import NetEaseApi
  File "/Users/rain/.wukong/contrib/sdk/NetEaseApi.py", line 21, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
2020-02-10 00:27:27,856 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 RaspberryPiStatus 加载成功 
2020-02-10 00:27:27,858 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Reboot 加载成功 
2020-02-10 00:27:27,859 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 RoadCondition 加载成功 
2020-02-10 00:27:27,860 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 SmartMiFan 加载成功 
2020-02-10 00:27:27,862 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 SpeakIP 加载成功 
2020-02-10 00:27:27,863 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 SpeakTemperature 加载成功 
2020-02-10 00:27:27,864 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 WOL 加载成功 
2020-02-10 00:27:27,866 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 Weather 加载成功 
2020-02-10 00:27:27,868 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 WeiBo 加载成功 
2020-02-10 00:27:27,870 - robot.plugin_loader - plugin_loader.py - init_plugins - line 66 - INFO - 插件 YouDaoFanYi 加载成功 
2020-02-10 00:27:27,871 - robot.Brain - Brain.py - printPlugins - line 51 - INFO - 已激活插件：['cleancache', 'Echo', 'email', 'Geek', 'LocalPlayer', 'poem', 'Volume', 'baidufm', 'BaiduMap', 'mqttPub', 'direction', 'emailmypc', 'halt', 'hass', 'headline_news', 'Lamp', 'pi_status', 'reboot', 'roadcondition', 'SmartMiFan', 'speak_ip', 'speak_temperature', 'wol', 'weather', 'WeiBo', 'youdao']
2020-02-10 00:27:27,873 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2020-02-10 00:28:09,484 - robot.AI - AI.py - chat - line 135 - INFO - emotibot 回答：吼！看到你每天精神满满的和我打招呼，我就觉得充满活力！
2020-02-10 00:28:11,434 - robot.TTS - TTS.py - get_speech - line 151 - INFO - baidu-tts 语音合成成功，合成路径：/var/folders/np/ql8g663d0_96tq6f6dz5f2zh0000gp/T/tmp35pjwv5z.mp3
2020-02-10 00:28:11,435 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2020-02-10 00:28:11,435 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 吼！看到你每天精神满满的和我打招呼，我就觉得充满活力！, http://0.0.0.0:5000/audio/8ca5f2ae3656e0012348ec7f311cb103.mp3
2020-02-10 00:28:27,292 - robot.AI - AI.py - chat - line 135 - INFO - emotibot 回答：我是谁？我是叮当啊，一个从云端网络来到你身边的专属精灵~
2020-02-10 00:28:28,525 - robot.TTS - TTS.py - get_speech - line 151 - INFO - baidu-tts 语音合成成功，合成路径：/var/folders/np/ql8g663d0_96tq6f6dz5f2zh0000gp/T/tmpmndg_17s.mp3
2020-02-10 00:28:28,527 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2020-02-10 00:28:28,527 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 我是谁？我是叮当啊，一个从云端网络来到你身边的专属精灵~, http://0.0.0.0:5000/audio/4536d640b8a6d9c2f3cf37dd2a5975a2.mp3

**Comment by goxofy** [comment]
@1341290135 你这个问题和我说的问题不是一回事吧

**Comment by goxofy** [comment]
@wzpan 可否有办法解决？

**Comment by 1341290135** [comment]
我的问题就是robot启动后，说完第一句话，然后向它说话没有应答，无法语音交互。但是后台直接发消息，可以反馈声音出来。

**Comment by wzpan** [comment]
@1341290135 你需要先唤醒它，如果唤醒不了，那就重新训练唤醒词。

**Comment by wzpan** [comment]
@goxofy 是不是没有更新到最新的插件版本，我看新版本在问完那句话后并不会进入主动聆听。

**Comment by 1341290135** [comment]
huangbodeMacBook-Pro:wukong-robot rain$ python3.7 wukong.py update
True

还是一样，偏好设置不用改吧。

![C1554804-BA29-4988-AA21-86842DD5C8C8](https://user-images.githubusercontent.com/14269481/74334097-35d86100-4dd4-11ea-896f-f2115114a8db.jpeg)

**Comment by goxofy** [comment]
> @goxofy 是不是没有更新到最新的插件版本，我看新版本在问完那句话后并不会进入主动聆听。

我拉取一下试试

**Comment by goxofy** [comment]
@wzpan 不只是这个网易云音乐插件的问题，只要是这种反问式的，比如说“我没有听清，请再说一次”，也是这种情况，没有时间说
