### ISSUE TITLE
打开wukong.py报错。

### ISSUE THREAD

**Issue by kiorry** [wzpan/wukong-robot#109]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

 Raspbian Buster

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

我用的是树莓派3B，装的系统是buster lite. 项目安装是能过git clone到本地，然后用pip3 install -r.
MIC是respeaker 2 mic，已经通过respeaker的录音，插入，还有demo测试过，没问题。也用snowboy的demo测试过，均可正常操作。

下面是我遇到的具体问题。
用python3打开wukong.py时报错如下 ：
pi@raspberrypi:~/wukong-robot/snowboy $ python3 ../wukong.py
Traceback (most recent call last):
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 15, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 18, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 17, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_snowboydetect'

因为提示是No module named '_snowboydetect'，我以为是snowboy的问题，把snowboy的测试用的文件 _snowboydetec.so 也拷过来，还是不行。
pi@raspberrypi:~/wukong-robot/snowboy $ ls
__init__.py  resources          snowboydetect.py
__pycache__  snowboydecoder.py  _snowboydetect.so

然后我以为是命名的原因，我把/wukong/snowboy/snowboydetect.py修改了一下，把第12行的
'_snowboydtect' 改成 'snowboydetect'.
报错如下：
Traceback (most recent call last):
  File "../wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 99, in <module>
    class SnowboyDetect(_object):
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 148, in SnowboyDetect
    __swig_destroy__ = _snowboydetect.delete_SnowboyDetect
AttributeError: module 'snowboy.snowboydetect' has no attribute 'delete_SnowboyDetect'

注释148行，再运行。
Traceback (most recent call last):
  File "../wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 150, in <module>
    SnowboyDetect_swigregister = _snowboydetect.SnowboyDetect_swigregister
AttributeError: module 'snowboy.snowboydetect' has no attribute 'SnowboyDetect_swigregister'

到这里，我发现一开始改名字的方法是错的，但我不知道要怎么解决。

**Comment by wzpan** [comment]
https://github.com/wzpan/wukong-robot/wiki/troubleshooting

**Comment by mrfanyilin** [comment]
@wzpan 我的运行的时候 报了一个 ImportError: No module named 'Crypto'

**Comment by wzpan** [comment]
@mrfanyilin 请更新插件到 1.6.0 新版本，最近合了个PR应该已经修复了这个问题了。

**Comment by mrfanyilin** [comment]
@wzpan 更新之后已修复，谢谢！
