### ISSUE TITLE
不能唤醒

### ISSUE THREAD

**Issue by Kevin369** [wzpan/wukong-robot#118]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Stretch

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

麦克风阵列录音、播放都没问题，集成悟空后出现不能播放声音和不能唤醒的问题，在snowboy官网录制声音后。按照Issue里面不能播放的步骤修改文件后可以播放声音，依然不能唤醒，snowboy官网录音的时候也没反应，麦克风阵列录音、播放再次确认都没问题。报错如下：

Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPeriodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934

File "/home/pi/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.wukong/contrib/NeteaseMusic.py", line 9, in <module>
    from robot.Player import MusicPlayer
ImportError: cannot import name 'MusicPlayer' from 'robot.Player' (/home/pi/wukong-robot/robot/Player.py)

2020-04-10 09:55:24,722 - robot.plugin_loader - WARNING - 插件 WeiBo 加载出错，跳过
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.wukong/contrib/WeiBo.py", line 4, in <module>
    from sdk.weibo import WeiBo
ModuleNotFoundError: No module named 'sdk'

**Comment by wzpan** [comment]
请检查下是否代码没有更到最新

**Comment by wzpan** [comment]
久无回复，先关闭了。如果有问题可继续提问。
