### ISSUE TITLE
Direction插件

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#14]
触发Direction技能,报错，错误如下
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/wukong/wukong-robot/robot/Player.py", line 91, in run
    self.onCompleted()
  File "/home/pi/.wukong/contrib/Direction.py", line 100, in <lambda>
    self.say("去哪里", cache=True, onCompleted=lambda: onAsk(self.activeListen()))
  File "/home/pi/.wukong/contrib/Direction.py", line 52, in onAsk
    res = self.request(url_place, params_place)
  File "/home/pi/.wukong/contrib/Direction.py", line 22, in request
    return json.loads(content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

我将content转为字符串后
`content=content.decode("utf-8")`
此错误没有了，又有新问题了。
我：“线路”；
悟空：“去哪里”；
我：“世纪大道”（在我说世纪大道的时候，叮叮声响了两次，悟空回复我的时候滴滴声也是两次）
2019-02-18 22:45:22,041 - Direction - ERROR - 位置接口:Parameter Invalid
ERROR:Direction:位置接口:Parameter Invalid
注明：悟空成功回复过我几次正确的线路规划，但是我在说世纪大道的时候，叮叮声响了两次，回复我的时候也是两次滴滴声，之后就是两个声音，而且一个是说线路规划，另一个在说别的东西。

**Comment by nameluck** [comment]
补充：
![image](https://user-images.githubusercontent.com/37497053/52983591-c630cf80-3426-11e9-9925-4c16c62044fb.png)
在我说要去哪的是录制两次，回复我线路规划的时候回答两次

**Comment by wzpan** [comment]
fixed
