### ISSUE TITLE
偶现通过语音唤醒，说出指令后会出现报错ERROR - Cannot write() after finish()，出现该问题后需要到管理后台中输入文字指令才能恢复正常。

### ISSUE THREAD

**Issue by iYongHsu** [wzpan/wukong-robot#157]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

Debian10

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

偶现通过语音唤醒，说出指令后会出现报错ERROR - Cannot write() after finish()，出现该问题后需要到管理后台中输入文字指令才能恢复正常。
具体报错如下（报错来自于使用hass技能插件和网易云音乐技能插件）：
>2021-06-21 23:53:42,090 - snowboy - snowboydecoder.py - start - line 345 - INFO - Keyword 1 detected at time: 2021-06-21 23:53:42
2021-06-21 23:53:43,123 - __main__ - wukong.py - start_record - line 78 - INFO - 开始录音
2021-06-21 23:53:46,408 - robot.Conversation - Conversation.py - converse - line 105 - INFO - 结束录音
2021-06-21 23:53:47,336 - robot.ASR - ASR.py - transcribe - line 106 - INFO - tencent-asr 语音识别到了：关闭热水器。
2021-06-21 23:53:49,058 - robot.Brain - Brain.py - query - line 72 - INFO - '关闭热水器。' 命中技能 hass
2021-06-21 23:53:49,299 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2021-06-21 23:53:49,301 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2021-06-21 23:53:49,302 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 设备执行成功, http://0.0.0.0:5000/audio/e02f16acdea3cc0ad5a2e29b4cf40398.wav
2021-06-21 23:53:49,304 - Hass - Hass.py - handle - line 118 - ERROR - Cannot write() after finish()
2021-06-21 23:53:49,308 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2021-06-21 23:53:49,309 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2021-06-21 23:53:49,310 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 对不起，指令不存在, http://0.0.0.0:5000/audio/fd74304a61ea1e3d4fad2721d9f2c135.wav
2021-06-21 23:53:49,311 - robot.Brain - Brain.py - query - line 85 - CRITICAL - Failed to execute plugin
Traceback (most recent call last):
  File "/root/wukong-robot/robot/Brain.py", line 81, in query
    continueHandle = plugin.handle(text, parsed)
  File "/root/.wukong/contrib/Hass.py", line 121, in handle
    self.say("对不起，指令不存在", cache=True)
  File "/root/wukong-robot/robot/sdk/AbstractPlugin.py", line 32, in say
    self.con.say(text, cache=cache, plugin=self.SLUG, onCompleted=onCompleted, wait=wait)
  File "/root/wukong-robot/robot/Conversation.py", line 200, in say
    self.onSay(msg, audio, plugin=plugin)
  File "/root/wukong-robot/server/server.py", line 112, in <lambda>
    conversation.doResponse(query, uuid, onSay=lambda msg, audio, plugin: self.onResp(msg, audio, plugin))
  File "/root/wukong-robot/server/server.py", line 100, in onResp
    self.write(json.dumps(res))
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 738, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
2021-06-21 23:53:49,315 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2021-06-21 23:53:49,316 - robot.Conversation - Conversation.py - say - line 197 - INFO - False
2021-06-21 23:53:49,317 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 抱歉，插件hass出故障了，晚点再试试吧, http://0.0.0.0:5000/audio/82fb598ba4af78c61bfab56d03d2ee0f.wav
2021-06-22 20:44:28,694 - snowboy - snowboydecoder.py - start - line 345 - INFO - Keyword 1 detected at time: 2021-06-22 20:44:28
2021-06-22 20:44:29,893 - __main__ - wukong.py - start_record - line 78 - INFO - 开始录音
2021-06-22 20:44:33,018 - robot.Conversation - Conversation.py - converse - line 105 - INFO - 结束录音
2021-06-22 20:44:34,625 - robot.ASR - ASR.py - transcribe - line 106 - INFO - tencent-asr 语音识别到了：网易云推荐歌曲。
2021-06-22 20:44:36,855 - robot.Brain - Brain.py - query - line 72 - INFO - '网易云推荐歌曲。' 命中技能 NeteaseMusic
2021-06-22 20:44:38,120 - robot.TTS - TTS.py - get_speech - line 189 - INFO - tencent-tts 语音合成成功，合成路径：/tmp/tmp5fahee9c.wav
2021-06-22 20:44:38,122 - robot.Conversation - Conversation.py - say - line 197 - INFO - False
2021-06-22 20:44:38,123 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 今天共有32首推荐歌曲噢！, http://0.0.0.0:5000/audio/6eb3eec2e2a3942ca1aba14a182aea2d.wav
2021-06-22 20:44:38,123 - NeteaseMusic - NeteaseMusic.py - handle - line 603 - ERROR - Cannot write() after finish()
2021-06-22 20:44:38,124 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2021-06-22 20:44:38,126 - robot.Conversation - Conversation.py - say - line 197 - INFO - True
2021-06-22 20:44:38,127 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 哎呀！处理语句出错 赶紧检查一下吧！, http://0.0.0.0:5000/audio/d32f94d696086b7c1aed222a4de4dc78.wav
2021-06-22 20:44:38,128 - robot.Brain - Brain.py - query - line 85 - CRITICAL - Failed to execute plugin
Traceback (most recent call last):
  File "/root/.wukong/contrib/NeteaseMusic.py", line 474, in handle
    self.say('今天共有{}首推荐歌曲噢！'.format(len(self.player.playlist)), wait=True)
  File "/root/wukong-robot/robot/sdk/AbstractPlugin.py", line 32, in say
    self.con.say(text, cache=cache, plugin=self.SLUG, onCompleted=onCompleted, wait=wait)
  File "/root/wukong-robot/robot/Conversation.py", line 200, in say
    self.onSay(msg, audio, plugin=plugin)
  File "/root/wukong-robot/server/server.py", line 112, in <lambda>
    conversation.doResponse(query, uuid, onSay=lambda msg, audio, plugin: self.onResp(msg, audio, plugin))
  File "/root/wukong-robot/server/server.py", line 100, in onResp
    self.write(json.dumps(res))
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 738, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()<br>
During handling of the above exception, another exception occurred:<br>
Traceback (most recent call last):
  File "/root/wukong-robot/robot/Brain.py", line 81, in query
    continueHandle = plugin.handle(text, parsed)
  File "/root/.wukong/contrib/NeteaseMusic.py", line 604, in handle
    self.say('哎呀！处理语句出错 赶紧检查一下吧！', cache=True)
  File "/root/wukong-robot/robot/sdk/AbstractPlugin.py", line 32, in say
    self.con.say(text, cache=cache, plugin=self.SLUG, onCompleted=onCompleted, wait=wait)
  File "/root/wukong-robot/robot/Conversation.py", line 200, in say
    self.onSay(msg, audio, plugin=plugin)
  File "/root/wukong-robot/server/server.py", line 112, in <lambda>
    conversation.doResponse(query, uuid, onSay=lambda msg, audio, plugin: self.onResp(msg, audio, plugin))
  File "/root/wukong-robot/server/server.py", line 100, in onResp
    self.write(json.dumps(res))
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 738, in write
    raise RuntimeError("Cannot write() after finish()")
RuntimeError: Cannot write() after finish()
2021-06-22 20:44:38,143 - robot.Conversation - Conversation.py - say - line 187 - INFO - 命中缓存，播放缓存语音
2021-06-22 20:44:38,144 - robot.Conversation - Conversation.py - say - line 197 - INFO - False
2021-06-22 20:44:38,145 - robot.Conversation - Conversation.py - say - line 199 - INFO - onSay: 抱歉，插件NeteaseMusic出故障了，晚点再试试吧, http://0.0.0.0:5000/audio/d4a2ea4644fe97750d8fd15b104f7e34.wav

**复现步骤**

偶尔触发。

**Comment by wzpan** [comment]
@iYongHsu 试试更新到 2.5.2 看看能否解决问题。

**Comment by wzpan** [comment]
久未回复，先关闭本 issue。
