### ISSUE TITLE
启动时报错 TypeError

### ISSUE THREAD

**Issue by fred913** [wzpan/wukong-robot#162]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**

Raspbian Buster

**离线唤醒相关**

非离线唤醒问题
—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

启动时报错
```
Traceback (most recent call last):
  File "wukong.py", line 275, in <module>
    wukong.run()
  File "wukong.py", line 118, in run
    self.init()
  File "wukong.py", line 49, in init
    self._conversation.say('{} 你好！试试对我喊唤醒词叫醒我吧'.format(config.get('first_name', '主人')), True)
  File "/root/wukong-robot/robot/Conversation.py", line 205, in say
    self.player.play(voice, not cache, onCompleted, wait)
  File "/root/wukong-robot/robot/Player.py", line 84, in play
    if os.path.exists(src) or src.startswith('http'):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
该报错已有一个issue，但不是同一个问题。配置文件格式完全正确（通过pyyaml校验过），经检查可能是语音合成出了什么问题。通过断点发现在调用self.player.play时voice值为None，且不调用self.onSay（audio未定义），剩下的仍在寻找错误原因

**Comment by fred913** [comment]
目前看 罪魁祸首是tts，因为tts返回的voice就是none

**Comment by fred913** [comment]
草，报错原因十分简单，tts已经有错误，所以返回了None，然而好像tts错误的log默认不显示出来。。

**Comment by fred913** [comment]
好了，非wukong-robot问题，关issue了。
百度TTS返回16: Open api characters limit reached
