### ISSUE TITLE
docker中启动wukong.py启动失败

### ISSUE THREAD

**Issue by tjuniversitywzy** [wzpan/wukong-robot#172]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

docker安装

**操作系统**

macOS Big Sur
版本11.4

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

mac上用docker启动wzpan/wukong-robot-arm:latest，报错（M1芯片的mac，采用wzpan/wukong-robot:latest也是如下报错）
Traceback (most recent call last):
  File "wukong.py", line 161, in <module>
    wukong.run()
  File "wukong.py", line 82, in run
    self.init()
  File "wukong.py", line 46, in init
    self._observer.start()
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/usr/local/lib/python3.5/dist-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/inotify_c.py", line 188, in __init__
    Inotify._raise_error()
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/inotify_c.py", line 417, in _raise_error
    raise OSError(os.strerror(err))
OSError: Function not implemented
求大神看看这个问题

**Comment by tjuniversitywzy** [comment]
更换其他系统后可以启动了
