### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by assassin0yxz** [wzpan/wukong-robot#2]
Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/wukong-robot/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _snowboydetect

**Comment by wzpan** [comment]
@assassin0yxz 你需要确保两个事情：

1. 使用 Python 3 执行本程序；
2. 确保用上了平台可用的 _snowboydetect.so 包。建议[自行编译](https://github.com/wzpan/wukong-robot/wiki/roadmap)一个。

**Comment by wzpan** [comment]
@FanXingGuo 你需要先安装 sox 。参见 [安装教程](https://github.com/wzpan/wukong-robot/wiki/install#2-%E5%AE%89%E8%A3%85-sox-)

**Comment by wzpan** [comment]
These problems should have been solved. Close this issue.
