### ISSUE TITLE
Mac下使用终端通过SSH连树莓派，运行 Python3 wukong.py 报错

### ISSUE THREAD

**Issue by ZhangJun1015** [wzpan/wukong-robot#20]
错误信息：
```
pi@Sirit:~/wukong-robot $ python3 wukong.py
Traceback (most recent call last):
  File "wukong.py", line 133, in <module>
    wukong.run()
  File "wukong.py", line 77, in run
    self.init()
  File "wukong.py", line 35, in init
    ''')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 84-92: ordinal not in range(128)
pi@Sirit:~/wukong-robot $ 
```

还有：
使用FinalShell可以正常运行 python3 wukong.py，但是语音识别不了唤醒词，这应该是需要重新训练唤醒词吧？

谢谢！

**Comment by Jesse54211** [comment]
可以现在配置文件里改改唤醒灵敏度为0.5(原来0.4)，效果提升了不少
