### ISSUE TITLE
树莓派安装后报错

### ISSUE THREAD

**Issue by weibinke** [wzpan/wukong-robot#238]
Player.doPlay这里在树莓派下用了play命令，应该是aplay？
   def doPlay(self, src):
        system = platform.system()
        if system == "Darwin":
            cmd = ["afplay", str(src)]
        else:
            cmd = ["aplay", str(src)]
        logger.debug("Executing %s", " ".join(cmd))

报错信息：
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/flybot/wukong-robot/robot/Player.py", line 103, in playLoop
    res = self.doPlay(src)
  File "/home/pi/flybot/wukong-robot/robot/Player.py", line 117, in doPlay
    self.proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'play'

**Comment by wzpan** [comment]
需要安装 sox
