### ISSUE TITLE
升级之后   后台聊天 流式请求报错

### ISSUE THREAD

**Issue by jwister** [wzpan/wukong-robot#253]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

Raspbian

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

**复现步骤**

只要在后台聊天框切换成openai聊天就报错 如下：
2023-04-27 03:54:37,659 - robot.Conversation - Conversation.py - _ttsAction - line 99 - ERROR - 语音合成失败：Cannot run the event loop while another loop is running
Stack (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/wukong-robot/server/server.py", line 497, in <lambda>
    t = threading.Thread(target=lambda: start_server(conversation, wukong))
  File "/root/wukong-robot/server/server.py", line 490, in start_server
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/netutil.py", line 262, in accept_handler
    callback(connection, address)
  File "/usr/local/lib/python3.7/dist-packages/tornado/tcpserver.py", line 294, in _handle_connection
    future = self.handle_stream(stream, address)
  File "/usr/local/lib/python3.7/dist-packages/tornado/httpserver.py", line 194, in handle_stream
    conn.start_serving(self)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 722, in start_serving
    self._serving_future = self._server_request_loop(delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 735, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 152, in read_response
    return self._read_message(delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.7/dist-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 2195, in finish
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 2228, in execute
    **self.path_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/root/wukong-robot/server/server.py", line 176, in post
    onStream=lambda data, resp_uuid: self.onStream(data, resp_uuid),
  File "/root/wukong-robot/robot/Conversation.py", line 170, in doResponse
    self.stream_say(stream, True, onCompleted=self.checkRestore)
  File "/root/wukong-robot/robot/Conversation.py", line 365, in stream_say
    audio = self._tts_line(line.strip(), cache, index, onCompleted)
  File "/root/wukong-robot/robot/Conversation.py", line 293, in _tts_line
    result = self._ttsAction(line, cache, index, onCompleted)
  File "/root/wukong-robot/robot/Conversation.py", line 99, in _ttsAction
    logger.error(f"语音合成失败：{e}", stack_info=True)
Traceback (most recent call last):
  File "/root/wukong-robot/robot/Conversation.py", line 84, in _ttsAction
    voice = self.tts.get_speech(msg)
  File "/root/wukong-robot/robot/TTS.py", line 373, in get_speech
    tmpfile = event_loop.run_until_complete(self.async_get_speech(phrase))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 529, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
2023-04-27 03:54:38,204 - robot.Conversation - Conversation.py - _ttsAction - line 99 - ERROR - 语音合成失败：Cannot run the event loop while another loop is running
Stack (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/wukong-robot/server/server.py", line 497, in <lambda>
    t = threading.Thread(target=lambda: start_server(conversation, wukong))
  File "/root/wukong-robot/server/server.py", line 490, in start_server
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/netutil.py", line 262, in accept_handler
    callback(connection, address)
  File "/usr/local/lib/python3.7/dist-packages/tornado/tcpserver.py", line 294, in _handle_connection
    future = self.handle_stream(stream, address)
  File "/usr/local/lib/python3.7/dist-packages/tornado/httpserver.py", line 194, in handle_stream
    conn.start_serving(self)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 722, in start_serving
    self._serving_future = self._server_request_loop(delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 735, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 152, in read_response
    return self._read_message(delegate)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.7/dist-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 2195, in finish
    self.execute()
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 2228, in execute
    **self.path_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/root/wukong-robot/server/server.py", line 176, in post
    onStream=lambda data, resp_uuid: self.onStream(data, resp_uuid),
  File "/root/wukong-robot/robot/Conversation.py", line 170, in doResponse
    self.stream_say(stream, True, onCompleted=self.checkRestore)
  File "/root/wukong-robot/robot/Conversation.py", line 365, in stream_say
    audio = self._tts_line(line.strip(), cache, index, onCompleted)
  File "/root/wukong-robot/robot/Conversation.py", line 293, in _tts_line
    result = self._ttsAction(line, cache, index, onCompleted)
  File "/root/wukong-robot/robot/Conversation.py", line 99, in _ttsAction
    logger.error(f"语音合成失败：{e}", stack_info=True)
Traceback (most recent call last):
  File "/root/wukong-robot/robot/Conversation.py", line 84, in _ttsAction
    voice = self.tts.get_speech(msg)
  File "/root/wukong-robot/robot/TTS.py", line 373, in get_speech
    tmpfile = event_loop.run_until_complete(self.async_get_speech(phrase))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 529, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running
2023-04-27 03:54:38,245 - robot.Conversation - Conversation.py - _after_play - line 335 - INFO - onSay: 我是一个人工智能机器人，专门为用户提供在线问答和虚拟助手服务。, []2023-04-27 03:54:38,247 - server.server - server.py - onResp - line 141 - INFO - response msg: 我是一个人工智能机器人，专门为用户提供在线问答和虚拟助手服务。

**Comment by Finley1991** [comment]
我也遇到了同样的错误：
2023-04-29 08:26:15,530 - robot.Conversation - Conversation.py - _ttsAction - line 99 - ERROR - 语音合成失败：Cannot run the event loop while another loop is running
Stack (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/server/server.py", line 497, in <lambda>
    t = threading.Thread(target=lambda: start_server(conversation, wukong))
  File "/app/server/server.py", line 490, in start_server
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.8/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tornado/netutil.py", line 262, in accept_handler
    callback(connection, address)
  File "/usr/local/lib/python3.8/site-packages/tornado/tcpserver.py", line 294, in _handle_connection
    future = self.handle_stream(stream, address)
  File "/usr/local/lib/python3.8/site-packages/tornado/httpserver.py", line 194, in handle_stream
    conn.start_serving(self)
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 722, in start_serving
    self._serving_future = self._server_request_loop(delegate)
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 735, in _server_request_loop
    ret = yield conn.read_response(request_delegate)
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 152, in read_response
    return self._read_message(delegate)
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.8/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python3.8/site-packages/tornado/routing.py", line 256, in finish
    self.delegate.finish()
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2195, in finish
    self.execute()
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 2227, in execute
    self.handler._execute(transforms, *self.path_args,
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/app/server/server.py", line 170, in post
    conversation.doResponse(
  File "/app/robot/Conversation.py", line 170, in doResponse
    self.stream_say(stream, True, onCompleted=self.checkRestore)
  File "/app/robot/Conversation.py", line 365, in stream_say
    audio = self._tts_line(line.strip(), cache, index, onCompleted)
  File "/app/robot/Conversation.py", line 293, in _tts_line
    result = self._ttsAction(line, cache, index, onCompleted)
  File "/app/robot/Conversation.py", line 99, in _ttsAction
    logger.error(f"语音合成失败：{e}", stack_info=True)
Traceback (most recent call last):
  File "/app/robot/Conversation.py", line 84, in _ttsAction
    voice = self.tts.get_speech(msg)
  File "/app/robot/TTS.py", line 373, in get_speech
    tmpfile = event_loop.run_until_complete(self.async_get_speech(phrase))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
2023-04-29 08:26:15,553 - robot.Conversation - Conversation.py - _after_play - line 335 - INFO - onSay: 你好！有什么需要我的帮助吗？, []

**Comment by wzpan** [comment]
同 #259 ，试试主干版本是否已解决。

**Comment by wzpan** [comment]
久未回复，先关闭本 issue 。

**Comment by jwister** [comment]
您的邮件已收到，谢谢。
