### ISSUE TITLE
本地音乐 播放错误

### ISSUE THREAD

**Issue by ZhangJun1015** [wzpan/wukong-robot#27]
本地音乐的目录已加修改完了，但是里面没有任何文件。让悟空播放【本地音乐】的时候报错：
```
INFO:__main__:开始录音
2019-03-01 15:10:22,116 - robot.Conversation - INFO - 结束录音
INFO:robot.Conversation:结束录音
2019-03-01 15:10:23,931 - robot.ASR - INFO - baidu-asr 语音识别到了：['本地音乐，']
INFO:robot.ASR:baidu-asr 语音识别到了：['本地音乐，']
2019-03-01 15:10:25,300 - robot.Brain - INFO - '本地音乐，' 命中技能 LocalPlayer
INFO:robot.Brain:'本地音乐，' 命中技能 LocalPlayer
2019-03-01 15:10:25,305 - LocalPlayer - INFO - []
INFO:LocalPlayer:[]
2019-03-01 15:10:25,307 - robot.Brain - CRITICAL - Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 75, in handle
    self.player.play()
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 19, in play
    path = self.playlist[self.idx]
IndexError: list index out of range
CRITICAL:robot.Brain:Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 75, in handle
    self.player.play()
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 19, in play
    path = self.playlist[self.idx]
IndexError: list index out of range
2019-03-01 15:10:25,757 - robot.TTS - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmp5hhzeb8u.mp3
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmp5hhzeb8u.mp3
```

应该是文件索引错误，播放音乐之前应该做个判断，检测是否存在音乐文件吧？

**Comment by ZhangJun1015** [comment]
【进展】
这是音乐路径，里面拷贝了三首mp3（被遗忘的时光 (蔡琴).mp3，出塞曲 (蔡琴).mp3，大海 (张雨生).mp3），对悟空说【本地音乐】，还是报错。
```
## 本地音乐插件
LocalPlayer:
    path: "/home/pi/Music"  # 本地音乐存放路径

```
【错误信息】
```
2019-03-01 15:30:14,152 - robot.ASR - INFO - baidu-asr 语音识别到了：['本地音乐，']
INFO:robot.ASR:baidu-asr 语音识别到了：['本地音乐，']
2019-03-01 15:30:15,254 - robot.Brain - INFO - '本地音乐，' 命中技能 LocalPlayer
INFO:robot.Brain:'本地音乐，' 命中技能 LocalPlayer
2019-03-01 15:30:15,256 - robot.Brain - CRITICAL - Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 75, in handle
    self.player.play()
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 19, in play
    path = self.playlist[self.idx]
IndexError: list index out of range
CRITICAL:robot.Brain:Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 75, in handle
    self.player.play()
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 19, in play
    path = self.playlist[self.idx]
IndexError: list index out of range

```

**Comment by ZhangJun1015** [comment]
【进展2】
悟空自动重新加载每个插件了，现在可以播放了。

**Comment by ZhangJun1015** [comment]
【报错】
```
2019-03-01 15:42:09,432 - robot.ASR - INFO - baidu-asr 语音识别到了：['调大音量，']
INFO:robot.ASR:baidu-asr 语音识别到了：['调大音量，']
2019-03-01 15:42:10,497 - robot.Brain - INFO - '调大音量，' 命中技能 LocalPlayer
INFO:robot.Brain:'调大音量，' 命中技能 LocalPlayer
2019-03-01 15:42:10,499 - robot.Brain - CRITICAL - Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 83, in handle
    word = self.nlu.getSlotWords(parsed, 'CHANGE_VOL', 'user_vd')[0]
IndexError: list index out of range
CRITICAL:robot.Brain:Failed to execute plugin
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/Brain.py", line 60, in query
    continueHandle = plugin.handle(text, parsed)
  File "/home/pi/wukong-robot/plugins/LocalPlayer.py", line 83, in handle
    word = self.nlu.getSlotWords(parsed, 'CHANGE_VOL', 'user_vd')[0]
IndexError: list index out of range
2019-03-01 15:42:11,119 - robot.TTS - INFO - baidu-tts 语音合成成功，合成路径：/tmp/tmpb1cfa8d6.mp3
INFO:robot.TTS:baidu-tts 语音合成成功，合成路径：/tmp/tmpb1cfa8d6.mp3

```

**Comment by wzpan** [comment]
fixed
