### ISSUE TITLE
网易云插件出错

### ISSUE THREAD

**Issue by zyqq** [wzpan/wukong-robot#274]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相
<img width="1156" alt="err" src="https://github.com/wzpan/wukong-robot/assets/15664576/31bfcd7f-6355-4e3e-9118-a64b9d731d82">
关解答。

**安装方式**

手动安装

**操作系统**
macbook pro Intel
（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

网易云插件出错，报错如下

line 71 - INFO - '我想听陈奕迅的红玫瑰。' 命中技能 NeteaseMusic
2023-06-26 02:00:57,517 - robot.Brain - Brain.py - query - line 83 - CRITICAL - Failed to execute plugin: 'int' object has no attribute 'isdigit'
Stack (most recent call last):
  File "/Users/echo/workspace/wukong-robot/wukong.py", line 188, in <module>
    wukong.run()
  File "/Users/echo/workspace/wukong-robot/wukong.py", line 95, in run
    detector.initDetector(self)
  File "/Users/echo/workspace/wukong-robot/robot/detector.py", line 103, in initDetector
    detector.start(
  File "/Users/echo/workspace/wukong-robot/snowboy/snowboydecoder.py", line 403, in start
    audio_recorder_callback(fname)
  File "/Users/echo/workspace/wukong-robot/robot/Conversation.py", line 218, in converse
    self.doConverse(fp, callback)
  File "/Users/echo/workspace/wukong-robot/robot/Conversation.py", line 229, in doConverse
    self.doResponse(query, callback, onSay, onStream)
  File "/Users/echo/workspace/wukong-robot/robot/Conversation.py", line 161, in doResponse
    if self._InGossip(query) or not self.brain.query(query, parsed):
  File "/Users/echo/workspace/wukong-robot/robot/Brain.py", line 83, in query
    logger.critical(f"Failed to execute plugin: {e}", stack_info=True)
Traceback (most recent call last):
  File "/Users/echo/workspace/wukong-robot/robot/Brain.py", line 80, in query
    continueHandle = plugin.handle(text, parsed)
  File "/Users/echo/.wukong/contrib/NeteaseMusic.py", line 455, in handle
    self.player = NeteaseMusicPlayer(None, self)
  File "/Users/echo/.wukong/contrib/NeteaseMusic.py", line 140, in __init__
    if self.login():
  File "/Users/echo/.wukong/contrib/NeteaseMusic.py", line 178, in login
    resp = self.api.login(self.account, self.md5pass)
  File "/Users/echo/.wukong/contrib/sdk/NetEaseApi.py", line 452, in login
    if username.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'
2023-06-26 02:00:57,519 - robot.Conversation - Conversation.py - say - line 398 - INFO - 即将朗读语音：抱歉，插件NeteaseMusic出故障了，晚点再试试吧

**复现步骤**

配置网易云插件的账号密码，之后使用网易云插件报错

**Comment by wzpan** [comment]
第三方插件不在维护范围内，可以联系插件开发者帮忙跟进。

**Comment by zyqq** [comment]
对应的作者是谁呢

**Comment by wzpan** [comment]
> 对应的作者是谁呢

@tonytan1701
