### ISSUE TITLE
配置时，运行wukong，robot包报错

### ISSUE THREAD

**Issue by xiashu4** [wzpan/wukong-robot#279]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
配置时，输入python3 wukong-robot.py 后，报一长串错误，但我检查了是有文件的，类似：python3 wukong.py 
Traceback (most recent call last):
  File "/home/xy/Desktop/wukongrobot/wukong-robot-master/wukong.py", line 11, in <module>
    from robot.Conversation import Conversation

**Comment by wzpan** [comment]
> python3 wukong-robot.py 

这个脚本名字不对吧。是 python3 wukong.py 呀。

**Comment by xiashu4** [comment]
> 

对，我是TAB补全的，我把完整的报错信息贴出来

环境是虚拟机，ubuntu22.04

xy@xy-virtual-machine:~/Desktop/wukongrobot/wukong-robot-master$ python3 wukong.py 
Traceback (most recent call last):
  File "/home/xy/Desktop/wukongrobot/wukong-robot-master/wukong.py", line 11, in <module>
    from robot.Conversation import Conversation
  File "/home/xy/Desktop/wukongrobot/wukong-robot-master/robot/Conversation.py", line 16, in <module>
    from robot.LifeCycleHandler import LifeCycleHandler
  File "/home/xy/Desktop/wukongrobot/wukong-robot-master/robot/LifeCycleHandler.py", line 9, in <module>
    from watchdog.observers import Observer

**Comment by wzpan** [comment]
具体的错误没有给全。下面的具体错误信息是啥？请帖完整的log

**Comment by njtyair** [comment]
Traceback (most recent call last):
  File "/home/parallels/work/wukong-robot/wukong.py", line 11, in <module>
    from robot.Conversation import Conversation
  File "/home/parallels/work/wukong-robot/robot/Conversation.py", line 16, in <module>
    from robot.LifeCycleHandler import LifeCycleHandler
  File "/home/parallels/work/wukong-robot/robot/LifeCycleHandler.py", line 9, in <module>
    from watchdog.observers import Observer
  File "/home/parallels/.local/lib/python3.10/site-packages/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/home/parallels/.local/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 76, in <module>
    from watchdog.observers.api import (
  File "/home/parallels/.local/lib/python3.10/site-packages/watchdog/observers/api.py", line 23, in <module>
    from watchdog.utils.bricks import SkipRepeatsQueue
  File "/home/parallels/.local/lib/python3.10/site-packages/watchdog/utils/bricks.py", line 175, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

**Comment by ai408** [comment]
@njtyair 请问解决了吗？

**Comment by yiyexy** [comment]
这个问题主要是由于你的python版本过高。
collections是python的基本模块，3.10中将这些类变换了位置，到了collection.abc下面：
<img width="781" alt="image" src="https://github.com/user-attachments/assets/8696927e-f6a8-4628-bfb8-8470c968f064">
<img width="830" alt="image" src="https://github.com/user-attachments/assets/7454cc8e-7197-4e3a-9ec3-170ba7ef69b0">

解决办法也很简单：

1. 降低python版本（感觉过于麻烦，不推荐）
2. 这个错误主要是watchdog这个库，因此推荐如下方式：

- 本地clone这个库：`git clone https://github.com/gorakhargosh/watchdog.git`
- 进入这个库之后，修改库版本tag为0.9.0: `git checkout tags/v0.9.0`
- 找到文件`watchdog/src/watchdog/utils/bricks.py`中第175行，修改为`    class OrderedSet(collections.abc.MutableSet):`
- 在watchdog文件夹下，重新安装这个库：`pip3 install .`

问题解决～
