### ISSUE TITLE
使用鲁班猫arm平台运行报错： Unsupported CPU: '0xd05'

### ISSUE THREAD

**Issue by robinleee** [wzpan/wukong-robot#320]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**
 Debian GNU/Linux 10 (buster)

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题：
cat@lubancat:~/wukong-robot$ python3 wukong.py

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*               当前版本号:  3.5.3                      *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端：http://0.0.0.0:5001
            如需退出，可以按 Ctrl-4 组合键

2024-03-23 19:36:26,604 - robot.ASR - ASR.py - get_engine_by_slug - line 295 - INFO - 使用 baidu-asr ASR 引擎
2024-03-23 19:36:26,608 - robot.AI - AI.py - get_robot_by_slug - line 452 - INFO - 使用 bing 对话机器人
2024-03-23 19:36:26,612 - robot.TTS - TTS.py - get_engine_by_slug - line 469 - INFO - 使用 edge-tts TTS 引擎
2024-03-23 19:36:26,614 - robot.NLU - NLU.py - get_engine_by_slug - line 222 - INFO - 使用 unit NLU 引擎
2024-03-23 19:36:26,632 - robot.plugin_loader - plugin_loader.py - init_plugins - line 57 - INFO - 插件 Camera 已被禁用
2024-03-23 19:36:26,640 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 CleanCache 加载成功
2024-03-23 19:36:26,647 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Echo 加载成功
2024-03-23 19:36:26,676 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Email 加载成功
2024-03-23 19:36:26,685 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Geek 加载成功
2024-03-23 19:36:26,692 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Gossip 加载成功
2024-03-23 19:36:26,701 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 LocalPlayer 加载成功
2024-03-23 19:36:26,708 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Poem 加载成功
2024-03-23 19:36:26,715 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Reminder 加载成功
2024-03-23 19:36:26,724 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Volume 加载成功
2024-03-23 19:36:26,728 - robot.Brain - Brain.py - printPlugins - line 54 - INFO - 已激活插件：['cleancache', 'Echo', 'email', 'geek', 'Gossip', 'LocalPlayer', 'poem', 'Reminder', 'Volume']
2024-03-23 19:36:26,761 - robot.Conversation - Conversation.py - say - line 398 - INFO - 即将朗读语音：师父 你好！试试对我喊唤醒词叫醒我吧
2024-03-23 19:36:26,767 - robot.Conversation - Conversation.py - _tts - line 305 - INFO - _tts
2024-03-23 19:36:28,402 - robot.TTS - TTS.py - async_get_speech - line 366 - INFO - edge-tts 语音合成成功，合成路径：/home/cat/wukong-robot/temp/09ab51a43a0143628bfde0197b1ea6a0.mp3
2024-03-23 19:36:28,417 - robot.Conversation - Conversation.py - _ttsAction - line 85 - INFO - 第0段TTS合成成功。msg: 师父 你好
2024-03-23 19:36:28,426 - robot.Conversation - Conversation.py - _ttsAction - line 90 - INFO - 即将播放第0段TTS。msg: 师父 你好
2024-03-23 19:36:28,429 - robot.Player - Player.py - playLoop - line 101 - INFO - 开始播放音频：/home/cat/wukong-robot/temp/09ab51a43a0143628bfde0197b1ea6a0.mp3
2024-03-23 19:36:28,569 - robot.TTS - TTS.py - async_get_speech - line 366 - INFO - edge-tts 语音合成成功，合成路径：/home/cat/wukong-robot/temp/a66030d0a9a44b92b9181dfefd979c6f.mp3
2024-03-23 19:36:28,580 - robot.Conversation - Conversation.py - _ttsAction - line 85 - INFO - 第1段TTS合成成功。msg: 试试对我喊唤醒词叫醒我吧
2024-03-23 19:36:28,585 - robot.Conversation - Conversation.py - _ttsAction - line 90 - INFO - 即将播放第1段TTS。msg: 试试对我喊唤醒词叫醒我吧
2024-03-23 19:36:28,772 - robot.detector - detector.py - initDetector - line 19 - INFO - 使用 porcupine 进行离线唤醒
Traceback (most recent call last):
  File "/home/cat/wukong-robot/wukong.py", line 188, in <module>
    wukong.run()
  File "/home/cat/wukong-robot/wukong.py", line 95, in run
    detector.initDetector(self)
  File "/home/cat/wukong-robot/robot/detector.py", line 21, in initDetector
    import pvporcupine
  File "/home/cat/.local/lib/python3.9/site-packages/pvporcupine/__init__.py", line 12, in <module>
    from ._factory import *
  File "/home/cat/.local/lib/python3.9/site-packages/pvporcupine/_factory.py", line 15, in <module>
    from ._util import *
  File "/home/cat/.local/lib/python3.9/site-packages/pvporcupine/_util.py", line 78, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/home/cat/.local/lib/python3.9/site-packages/pvporcupine/_util.py", line 71, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/home/cat/.local/lib/python3.9/site-packages/pvporcupine/_util.py", line 62, in _pv_linux_machine
    raise NotImplementedError("Unsupported CPU: '%s'." % cpu_part)
NotImplementedError: Unsupported CPU: '0xd05'.
2024-03-23 19:36:30,746 - robot.Player - Player.py - doPlay - line 125 - INFO - 播放完成：/home/cat/wukong-robot/temp/09ab51a43a0143628bfde0197b1ea6a0.mp3
2024-03-23 19:36:30,749 - robot.Player - Player.py - playLoop - line 101 - INFO - 开始播放音频：/home/cat/wukong-robot/temp/a66030d0a9a44b92b9181dfefd979c6f.mp3
2024-03-23 19:36:34,090 - robot.Player - Player.py - doPlay - line 125 - INFO - 播放完成：/home/cat/wukong-robot/temp/a66030d0a9a44b92b9181dfefd979c6f.mp3

**Comment by ssssssssssshuai** [comment]
您好，您的这个问题解决了吗？方便交流一下？

**Comment by akorin12138** [comment]
https://github.com/Picovoice/porcupine/issues/1016#issuecomment-1601752586  官方没有支持的打算

**Comment by jack9603301** [comment]
试试看arm的虚拟化功能
