### ISSUE TITLE
ValueError: access_key should be a non-empty string.

### ISSUE THREAD

**Issue by super2013sky** [wzpan/wukong-robot#323]
**安装方式**

手动安装

**操作系统**

Ubuntu22.04

**离线唤醒相关**

**问题描述**

具体说明下问题
ValueError: access_key should be a non-empty string.
请问在哪里修改access_key

具体log如下：
Traceback (most recent call last):
  File "/home/rob/github/wukong/wukong-robot/wukong.py", line 188, in <module>
    wukong.run()
  File "/home/rob/github/wukong/wukong-robot/wukong.py", line 95, in run
    detector.initDetector(self)
  File "/home/rob/github/wukong/wukong-robot/robot/detector.py", line 28, in initDetector
    porcupine = pvporcupine.create(
  File "/home/rob/anaconda3/envs/wukong/lib/python3.9/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/home/rob/anaconda3/envs/wukong/lib/python3.9/site-packages/pvporcupine/_porcupine.py", line 143, in __init__
    raise ValueError("access_key should be a non-empty string.")
ValueError: access_key should be a non-empty string.

**Comment by wzpan** [comment]
<img width="496" alt="image" src="https://github.com/wzpan/wukong-robot/assets/1631405/b296c28b-f5fa-42d3-9364-3c72858b1d54">
access_key 需要填写。

**Comment by vdogmcgee** [comment]
请问一下填写access key的路径在哪里呢？ 以及默认的唤醒词是什么呢？

**Comment by vdogmcgee** [comment]
楼主能分享下你在ubuntu22.04手动安装的步骤吗，我照着官方的教程死活装不上，swig那里一直提示我找不到目录，感谢！

**Comment by litte-lucky-star** [comment]
> <img alt="图像" width="496" src="https://private-user-images.githubusercontent.com/1631405/322381210-b296c28b-f5fa-42d3-9364-3c72858b1d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODI3NTksIm5iZiI6MTcyNzY4MjQ1OSwicGF0aCI6Ii8xNjMxNDA1LzMyMjM4MTIxMC1iMjk2YzI4Yi1mNWZhLTQyZDMtOTM2NC0zYzcyODU4YjFkNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDc0NzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFjMDlhY2I0ZjhlZTA1MjQ5NmY4MWNkMWZjYTZjMGI4ZTRjYTkxMjNhNTFiMDI0MTEwODM3MDgyYmJjYjQwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YRE-MESan50JcoQq7VLvu-PXmQaJL1YJ5TgU0UVyenQ">
> access_key 需要填写。

大佬为啥我填完access key 还是报错File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_porcupine.py", line 158, in __init__
    raise IOError("Couldn't find keyword file at '%s'." % x)
![Uploading 屏幕截图 2024-09-30 163714.png…]()

**Comment by litte-lucky-star** [comment]
> <img alt="图像" width="496" src="https://private-user-images.githubusercontent.com/1631405/322381210-b296c28b-f5fa-42d3-9364-3c72858b1d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODU5MDUsIm5iZiI6MTcyNzY4NTYwNSwicGF0aCI6Ii8xNjMxNDA1LzMyMjM4MTIxMC1iMjk2YzI4Yi1mNWZhLTQyZDMtOTM2NC0zYzcyODU4YjFkNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDg0MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZiMWRlZjdmNzFmN2ExYTAxMGMxYzM3YmI4ZDRjMDljN2UxNThhYzRkZDZiNWM0ZTg4NzQ1ZGM3ZDRlYjk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.buJ_UK5qWgT9G6g_QeYZ8Dr-k1yXdnL8IqEsfTDZVFA">
> access_key 需要填写。

![屏幕截图 2024-09-30 163714](https://github.com/user-attachments/assets/63a013fb-790a-4315-ac6d-9fafa5d61a38)
大佬为啥我填完access key 还是报错File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_porcupine.py", line 158, in init
raise IOError("Couldn't find keyword file at '%s'." % x)

**Comment by DT-stone** [comment]
> > <img alt="图像" width="496" src="https://private-user-images.githubusercontent.com/1631405/322381210-b296c28b-f5fa-42d3-9364-3c72858b1d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODU5MDUsIm5iZiI6MTcyNzY4NTYwNSwicGF0aCI6Ii8xNjMxNDA1LzMyMjM4MTIxMC1iMjk2YzI4Yi1mNWZhLTQyZDMtOTM2NC0zYzcyODU4YjFkNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDg0MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZiMWRlZjdmNzFmN2ExYTAxMGMxYzM3YmI4ZDRjMDljN2UxNThhYzRkZDZiNWM0ZTg4NzQ1ZGM3ZDRlYjk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.buJ_UK5qWgT9G6g_QeYZ8Dr-k1yXdnL8IqEsfTDZVFA">
> > access_key需要填写。
> 
> ![屏幕截图 2024-09-30 163714](https://private-user-images.githubusercontent.com/181832362/372011034-63a013fb-790a-4315-ac6d-9fafa5d61a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTc0MzYsIm5iZiI6MTcyOTA5NzEzNiwicGF0aCI6Ii8xODE4MzIzNjIvMzcyMDExMDM0LTYzYTAxM2ZiLTc5MGEtNDMxNS1hYzZkLTlmYWZhNWQ2MWEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNjQ1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGU2ZDA5YWZlMWZlNWRlNTNjNjg3MjkxNWE4YzYzM2QwZTQ5YjJkZTQ5YTQ2OGVhMGU4OGRkNjJiNTNmYmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.faCEMnj0WtCTuiEY5PIZKru8DkhMI45HDODyiHbUYJc) 大佬为啥我填完access key还是报错File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_porcupine.py", line 158, in init raise IOError("Couldn't find keywords file在“%s”。" % x)

老哥hello-bing_en_raspberry-pi_v3_0_0.ppn 找不到的问题解决了吗

**Comment by SilaLiu** [comment]
> 楼主能分享下你在ubuntu22.04手动安装的步骤吗，我照着官方的教程死活装不上，swig那里一直提示我找不到目录，感谢！

这个要源码编译一个

**Comment by SilaLiu** [comment]
> <img alt="image" width="496" src="https://private-user-images.githubusercontent.com/1631405/322381210-b296c28b-f5fa-42d3-9364-3c72858b1d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjYzNDgsIm5iZiI6MTczMDM2NjA0OCwicGF0aCI6Ii8xNjMxNDA1LzMyMjM4MTIxMC1iMjk2YzI4Yi1mNWZhLTQyZDMtOTM2NC0zYzcyODU4YjFkNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzFUMDkxNDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFmOGE2MzI0MjIzMjk1OTk0ZWVkM2VjZDNjOGUyOTVhMTBiYTYxODJmZmEyNjllMjAxNTQ0ODJmMTI4ZmIwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hCDVJPqF-1zgUGqtqturqJ1mnQugZ3z3y-WeRTj1Qf8">
> access_key 需要填写。



> > <img alt="图像" width="496" src="https://private-user-images.githubusercontent.com/1631405/322381210-b296c28b-f5fa-42d3-9364-3c72858b1d54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODU5MDUsIm5iZiI6MTcyNzY4NTYwNSwicGF0aCI6Ii8xNjMxNDA1LzMyMjM4MTIxMC1iMjk2YzI4Yi1mNWZhLTQyZDMtOTM2NC0zYzcyODU4YjFkNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDg0MDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZiMWRlZjdmNzFmN2ExYTAxMGMxYzM3YmI4ZDRjMDljN2UxNThhYzRkZDZiNWM0ZTg4NzQ1ZGM3ZDRlYjk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.buJ_UK5qWgT9G6g_QeYZ8Dr-k1yXdnL8IqEsfTDZVFA">
> > access_key 需要填写。
> 
> ![屏幕截图 2024-09-30 163714](https://private-user-images.githubusercontent.com/181832362/372011034-63a013fb-790a-4315-ac6d-9fafa5d61a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNjYzNDgsIm5iZiI6MTczMDM2NjA0OCwicGF0aCI6Ii8xODE4MzIzNjIvMzcyMDExMDM0LTYzYTAxM2ZiLTc5MGEtNDMxNS1hYzZkLTlmYWZhNWQ2MWEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQwOTE0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQ3M2NmYzc5Yzc3MTYyMWZiNTBiNDM2MWIxMjRiNjAwMWIxMGFjM2I3YWVlZDgyODYzYjNlYzRkMjliYzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Pp6dshZZoIUHALex-QcLE4kaAizE-9Z8zPF-5iAizck) 大佬为啥我填完access key 还是报错File "/usr/local/lib/python3.9/dist-packages/pvporcupine/_porcupine.py", line 158, in init raise IOError("Couldn't find keyword file at '%s'." % x)

我也是这样的，请问大佬解决了吗
