### ISSUE TITLE
porcupine离线唤醒之前一直正常使用，突然就报错，请问怎么解决

### ISSUE THREAD

**Issue by wgqabc** [wzpan/wukong-robot#327]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**
porcupine离线唤醒之前一直正常使用，突然就报错，没做任何修改

具体说明下问题
Traceback (most recent call last):
  File "wukong-robot/wukong.py", line 189, in <module>
    wukong.run()
  File "wukong-robot/wukong.py", line 96, in run
    detector.initDetector(self)
  File "/home/bcorerobot/wukong-robot/robot/detector.py", line 28, in initDetector
    porcupine = pvporcupine.create(
  File "/home/bcorerobot/.local/lib/python3.8/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/home/bcorerobot/.local/lib/python3.8/site-packages/pvporcupine/_porcupine.py", line 198, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status](
pvporcupine._porcupine.PorcupineActivationRefusedError: Initialization failed:
  [0] Picovoice Error (code `00000136`)
  [1] Picovoice Error (code `00000136`)
  [2] Picovoice Error (code `00000136`)

**Comment by goodman3654** [comment]
估计是帐号被封了，换个帐号试试
