### ISSUE TITLE
运行报错:symbol not found in flat namespace

### ISSUE THREAD

**Issue by bryanleeli** [wzpan/wukong-robot#337]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装

**操作系统**
Macos
（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
运行python wukong.py报错如下:

Traceback (most recent call last):
  File "wukong.py", line 11, in <module>
    from robot.Conversation import Conversation
  File "/Users/myname/wukong-robot/robot/Conversation.py", line 16, in <module>
    import snowboydecoder
  File "/Users/myname/wukong-robot/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/Users/myname/wukong-robot/snowboy/snowboydetect.py", line 12, in <module>
    import _snowboydetect
ImportError: dlopen(/Users/myname/wukong-robot/snowboy/_snowboydetect.so, 0x0002): symbol not found in flat namespace '__ZN7snowboy10SnowboyVad12SetAudioGainEf'

**Comment by dreamboy2023** [comment]
> snowboy 不支持 M 系列芯片

有替代方案吗？
