### ISSUE TITLE
唤醒不了

### ISSUE THREAD

**Issue by SilaLiu** [wzpan/wukong-robot#342]
我在ubuntu22.04上运行起来了，但是运行wukong.py文件之后是以下这样的；是需要唤醒吗？我录制唤醒词了，还是不可以；在后台管理系统里输入唤醒词也是抱错：“抱歉, bing回答失败”
麻烦大佬解答一下。

********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*               当前版本号:  3.5.3                      *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            后台管理端:http://0.0.0.0:5001
            如需退出，可以按 Ctrl-4 组合键

2024-10-31 16:22:34,566 - robot.ASR - ASR.py - get_engine_by_slug - line 319 - INFO - 使用 baidu-asr ASR 引擎
2024-10-31 16:22:34,566 - robot.AI - AI.py - get_robot_by_slug - line 600 - INFO - 使用 bing 对话机器人
2024-10-31 16:22:34,566 - robot.TTS - TTS.py - get_engine_by_slug - line 469 - INFO - 使用 edge-tts TTS 引擎
2024-10-31 16:22:34,566 - robot.NLU - NLU.py - get_engine_by_slug - line 222 - INFO - 使用 unit NLU 引擎
2024-10-31 16:22:34,567 - robot.plugin_loader - plugin_loader.py - init_plugins - line 57 - INFO - 插件 Camera 已被禁用
2024-10-31 16:22:34,567 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 CleanCache 加载成功 
2024-10-31 16:22:34,568 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Echo 加载成功 
2024-10-31 16:22:34,570 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Email 加载成功 
2024-10-31 16:22:34,571 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Geek 加载成功 
2024-10-31 16:22:34,571 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Gossip 加载成功 
2024-10-31 16:22:34,572 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 LocalPlayer 加载成功 
2024-10-31 16:22:34,572 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Poem 加载成功 
2024-10-31 16:22:34,573 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Reminder 加载成功 
2024-10-31 16:22:34,573 - robot.plugin_loader - plugin_loader.py - init_plugins - line 61 - INFO - 插件 Volume 加载成功 
2024-10-31 16:22:34,574 - robot.Brain - Brain.py - printPlugins - line 54 - INFO - 已激活插件：['cleancache', 'Echo', 'email', 'geek', 'Gossip', 'LocalPlayer', 'poem', 'Reminder', 'Volume']
2024-10-31 16:22:34,578 - robot.Conversation - Conversation.py - say - line 398 - INFO - 即将朗读语音：老师 你好！试试对我喊唤醒词叫醒我吧
2024-10-31 16:22:34,579 - robot.Conversation - Conversation.py - _tts - line 305 - INFO - _tts
2024-10-31 16:22:35,603 - robot.TTS - TTS.py - async_get_speech - line 366 - INFO - edge-tts 语音合成成功，合成路径：/home/spark_ai/myenv/src/wukong-robot/temp/e60481b2529946d0af231cea34d5dde9.mp3
2024-10-31 16:22:35,604 - robot.Conversation - Conversation.py - _ttsAction - line 85 - INFO - 第1段TTS合成成功。msg: 试试对我喊唤醒词叫醒我吧
2024-10-31 16:22:35,725 - robot.TTS - TTS.py - async_get_speech - line 366 - INFO - edge-tts 语音合成成功，合成路径：/home/spark_ai/myenv/src/wukong-robot/temp/8f25dc12c7a94dbbaed421056a4a9d9e.mp3
2024-10-31 16:22:35,772 - robot.Conversation - Conversation.py - _ttsAction - line 85 - INFO - 第0段TTS合成成功。msg: 老师 你好
2024-10-31 16:22:35,783 - robot.Conversation - Conversation.py - _ttsAction - line 90 - INFO - 即将播放第0段TTS。msg: 老师 你好
2024-10-31 16:22:35,798 - robot.Conversation - Conversation.py - _ttsAction - line 90 - INFO - 即将播放第1段TTS。msg: 试试对我喊唤醒词叫醒我吧
2024-10-31 16:22:35,798 - robot.Player - Player.py - playLoop - line 101 - INFO - 开始播放音频：/home/spark_ai/myenv/src/wukong-robot/temp/8f25dc12c7a94dbbaed421056a4a9d9e.mp3
2024-10-31 16:22:35,820 - robot.Player - Player.py - doPlay - line 125 - INFO - 播放完成：/home/spark_ai/myenv/src/wukong-robot/temp/8f25dc12c7a94dbbaed421056a4a9d9e.mp3
2024-10-31 16:22:35,824 - robot.Player - Player.py - playLoop - line 101 - INFO - 开始播放音频：/home/spark_ai/myenv/src/wukong-robot/temp/e60481b2529946d0af231cea34d5dde9.mp3
2024-10-31 16:22:35,826 - robot.detector - detector.py - initDetector - line 19 - INFO - 使用 porcupine 进行离线唤醒
Traceback (most recent call last):
  File "/home/myenv/src/wukong-robot/wukong.py", line 188, in <module>
    wukong.run()
  File "/home/spark_ai/myenv/src/wukong-robot/wukong.py", line 95, in run
    detector.initDetector(self)
  File "/home/spark_ai/myenv/src/wukong-robot/robot/detector.py", line 28, in initDetector
    porcupine = pvporcupine.create(
  File "/home/spark_ai/myenv/lib/python3.10/site-packages/pvporcupine/_factory.py", line 69, in create
    return Porcupine(
  File "/home/spark_ai/myenv/lib/python3.10/site-packages/pvporcupine/_porcupine.py", line 143, in __init__
    raise ValueError("access_key should be a non-empty string.")
ValueError: access_key should be a non-empty string.
2024-10-31 16:22:35,837 - robot.Player - Player.py - doPlay - line 125 - INFO - 播放完成：/home/spark_ai/myenv/src/wukong-robot/temp/e60481b2529946d0af231cea34d5dde9.mp3

**Comment by wzpan** [comment]
报错里提到 porcupine 的 access_key 需要配置。你需要在 ~/.wukong/config.yml 里做相应配置：

![image](https://github.com/user-attachments/assets/3431519d-5708-4108-bc52-076f8a0a9330)
