### ISSUE TITLE
OSError: Couldn't find keyword file at '/home/pixbus/.wukong/hello-bing_en_raspberry-pi_v3_0_0.ppn'.

### ISSUE THREAD

**Issue by SilaLiu** [wzpan/wukong-robot#343]
**确认已寻找过答案**

我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。

**安装方式**

手动安装/docker安装

**操作系统**

（例如 Raspbian Stretch、Ubuntu 16.04）

**离线唤醒相关**

如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题
我已经使用百度以及讯飞的API进行了config.yml文件的修改，以及tts_engine: xunfei-tts、asr_engine: xunfei-asr都配置为讯飞的了，为什么还是报这个错误呢，porcupine 离线唤醒我也注册了，并且也给了access_key的值。
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/57119c1e-03e0-4f86-b05e-2f5b04e0180a">

**Comment by SilaLiu** [comment]
> **确认已寻找过答案**
> 
> 我已确认在 [Github issue](https://github.com/wzpan/wukong-robot/issues) 页、[常见问题](https://github.com/wzpan/wukong-robot/wiki/troubleshooting)页、[文档](http://wukong.hahack.com) 中都查找过，没有找到类似问题和资料。我也没有 google / bing/ 百度 / duckduckgo 到相关解答。
> 
> **安装方式**
> 
> 手动安装/docker安装
> 
> **操作系统**
> 
> （例如 Raspbian Stretch、Ubuntu 16.04）
> 
> **离线唤醒相关**
> 
> 如果是离线唤醒相关的问题，是否已确保 `arecord temp.wav`、`aplay temp.wav` (Linux) 或 `rec temp.wav`、`play temp.wav` （Mac）已正常工作？（注意要求不能带任何其他参数）如果不能，请先配置好麦克风和音响再尝试。
> 
> —— 我已确保录音、播放都正常工作才尝试 wukong-robot 。
> 
> **问题描述**
> 
> 具体说明下问题 我已经使用百度以及讯飞的API进行了config.yml文件的修改，以及tts_engine: xunfei-tts、asr_engine: xunfei-asr都配置为讯飞的了，为什么还是报这个错误呢，porcupine 离线唤醒我也注册了，并且也给了access_key的值。 <img alt="image" width="1431" src="https://private-user-images.githubusercontent.com/39790272/382158227-57119c1e-03e0-4f86-b05e-2f5b04e0180a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzExNTQsIm5iZiI6MTczMDQzMDg1NCwicGF0aCI6Ii8zOTc5MDI3Mi8zODIxNTgyMjctNTcxMTljMWUtMDNlMC00Zjg2LWIwNWUtMmY1YjA0ZTAxODBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAzMTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Y2FkYTYxZDc5NDYxNDg4NjZhOWYzYTNiZmRjMDNkODEzN2I4MTAyY2NhMGM5ZDFkYTZmOGZiZTM1MDcwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lw_-JTZvmRaS44M0DcjWwrwGBtS_lsmauH68HyasRQo">

**Comment by SilaLiu** [comment]
OK，是我粗心大意的问题，没有在配置文件目录下放唤醒文件，现在可以唤醒了，但是有一个问题，2024-11-01 11:13:00,318 - robot.Conversation - Conversation.py - say - line 398 - INFO - 即将朗读语音：没听清呢
2024-11-01 11:13:00,319 - robot.Conversation - Conversation.py - _tts - line 305 - INFO - _tts
2024-11-01 11:13:00,319 - robot.Conversation - Conversation.py - _ttsAction - line 99 - ERROR - 语音合成失败：module 'websocket' has no attribute 'enableTrace'
Stack (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pixbus/pix/robobus/HMI/spark_ai/myenv/src/wukong-robot/robot/Conversation.py", line 99, in _ttsAction
    logger.error(f"语音合成失败：{e}", stack_info=True)
Traceback (most recent call last):
  File "/home/pixbus/pix/robobus/HMI/spark_ai/myenv/src/wukong-robot/robot/Conversation.py", line 84, in _ttsAction
    voice = self.tts.get_speech(msg)
  File "/home/pixbus/pix/robobus/HMI/spark_ai/myenv/src/wukong-robot/robot/TTS.py", line 311, in get_speech
    return XunfeiSpeech.synthesize(
  File "/home/pixbus/pix/robobus/HMI/spark_ai/myenv/src/wukong-robot/robot/sdk/XunfeiSpeech.py", line 333, in synthesize
    websocket.enableTrace(False)
AttributeError: module 'websocket' has no attribute 'enableTrace'
2024-11-01 11:13:01,452 - robot.Player - Player.py - doPlay - line 125 - INFO - 播放完成：/home/pixbus/pix/robobus/HMI/spark_ai/myenv/src/wukong-robot/static/beep_lo.wav
