### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by guoweibo** [wzpan/wukong-robot#74]
启动报错,能帮忙看下,谢谢
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/pi/wukong-robot/robot/Player.py", line 81, in run
    self.pipe = subprocess.Popen(cmd, stdout=f, stderr=f)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'play'

**安装方式**
一键脚本

**操作系统**

Raspbian 

**离线唤醒相关**

—— 我已确保录音、播放都正常工作才尝试 wukong-robot 。

**问题描述**

具体说明下问题

**Comment by LA-0240** [comment]
我也是类似的问题，怎么解决的？
拜托了🙏
