### ISSUE TITLE
树莓派启动出现问题

### ISSUE THREAD

**Issue by FanXingGuo** [wzpan/wukong-robot#8]
pi@raspberrypi:~/wukong $ python3 wukong.py
Traceback (most recent call last):
  File "/home/pi/wukong/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/pi/wukong/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/pi/wukong/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/wukong/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by wzpan** [comment]
snowboy 的问题请访问：https://github.com/Kitt-AI/snowboy/issues/262
